### ISSUE TITLE
PHP extends issues

### ISSUE THREAD

**Issue by rgazelot** [thephpleague/oauth1-trello#1]
Hello, some methods from the abstract do not respect the abstract privacy. Like [createResourceOwner](https://github.com/thephpleague/oauth1-trello/blob/master/src/Server/Trello.php#L73) which should be `public` and not `protected`. The repo is unusable.

**Comment by stevenmaguire** [comment]
Thanks for the note @rgazelot. Are you aware that this repo is meant to be used in conjunction with its upstream package [thephpleague/oauth1-client](https://github.com/thephpleague/oauth1-client)? This package alone is a Trello adapter for that upstream package. Are you following the implementation instructions for the core package? If you are trying to extend this package directly and running into method visibility issues then that is expected behavior because it assumes you are using it in the context of the upstream package.

> The repo is unusable.

Perhaps you are trying to use the repo in a way it is not designed to be used?

**Comment by rgazelot** [comment]
@stevenmaguire Ok I didn't see that I have to use the upstream package. I tried to use it the same way the OAuth2 packages work. Thank for your answer ;)

**Comment by stevenmaguire** [comment]
No problem. Unfortunately, this oauth1-client package is not designed like the oauth2-client package.
